app:
  hostname: localhost
  server-port: 8761
  application-name: discovery-server

spring:
  application:
    name: ${app.application-name}
  profiles:
    active:
      - local

server:
  port: ${app.server-port}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${app.hostname}:${app.server-port}/eureka
  instance:
    hostname: ${app.hostname}}
  server:
    expected-client-renewal-interval-seconds: 5
    use-read-only-response-cache: false

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"